// ============================================================
// MOCK DATA — affichés quand l'API ne retourne aucun résultat
// ============================================================

export const MOCK_SHOPS = [
  {
    id: "mock-1",
    name: "Épicerie du Centre",
    description: "Votre épicerie de proximité au cœur de Kindu. Produits frais, boissons, conserves et bien plus encore.",
    city: "Kindu",
    category: "Alimentation",
    logo_url: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&q=80",
    address: "Avenue du Marché, Quartier Centre, Kindu",
    opening_hours: "Lun-Sam 07h00-20h00",
    owner_name: "Jean-Pierre Mbumba",
    phone: "+243 XXX XXX",
    is_mock: true,
  },
  {
    id: "mock-2",
    name: "Boutique Mode Kindu",
    description: "Les meilleures tendances vestimentaires pour femmes, hommes et enfants. Tissus africains et prêt-à-porter.",
    city: "Kindu",
    category: "Habillement",
    logo_url: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&q=80",
    address: "Avenue Kabambare, Quartier Kasuku, Kindu",
    opening_hours: "Lun-Ven 08h00-18h00",
    owner_name: "Marie Kasongo",
    phone: "+243 XXX XXX",
    is_mock: true,
  },
  {
    id: "mock-3",
    name: "Salon Beauté Kindu",
    description: "Salon de coiffure et soins de beauté pour femmes et hommes. Tresses, coupe, soin de peau et manucure.",
    city: "Kindu",
    category: "Beauté & Soins",
    logo_url: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400&q=80",
    address: "Quartier Alunguli, Kindu",
    opening_hours: "Lun-Sam 08h00-19h00",
    owner_name: "Claudine Nzigire",
    phone: "+243 XXX XXX",
    is_mock: true,
  },
  {
    id: "mock-4",
    name: "Tech & Électronique",
    description: "Vente et réparation d'appareils électroniques : téléphones, ordinateurs, accessoires et pièces détachées.",
    city: "Kindu",
    category: "Électronique",
    logo_url: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80",
    address: "Avenue Lualaba, Centre Commercial, Kindu",
    opening_hours: "Lun-Sam 08h00-18h30",
    owner_name: "Pascal Mukendi",
    phone: "+243 XXX XXX",
    is_mock: true,
  },
  {
    id: "mock-5",
    name: "Pharmacie Solidarité",
    description: "Médicaments, produits parapharmaceutiques et conseils santé. Pharmaciens diplômés à votre service.",
    city: "Kindu",
    category: "Santé",
    logo_url: "https://images.unsplash.com/photo-1576671081837-49000212a370?w=400&q=80",
    address: "Avenue de l'Hôpital, Kindu",
    opening_hours: "Lun-Dim 07h00-21h00",
    owner_name: "Dr. Aline Bahati",
    phone: "+243 XXX XXX",
    is_mock: true,
  },
  {
    id: "mock-6",
    name: "Restaurant Mama Léonie",
    description: "Cuisine congolaise authentique : fufu, pondu, moambe, poisson braisé. Livraison possible dans Kindu.",
    city: "Kindu",
    category: "Restauration",
    logo_url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&q=80",
    address: "Quartier Mbilizi, Kindu",
    opening_hours: "Tous les jours 10h00-22h00",
    owner_name: "Léonie Kalala",
    phone: "+243 XXX XXX",
    is_mock: true,
  },
];

export const MOCK_PRODUCTS = [
  {
    id: "mock-p1",
    name: "Sac de riz (25 kg)",
    description: "Riz blanc de qualité supérieure, importé. Idéal pour les familles et les restaurants. Grain long et parfumé.",
    price: "45000",
    category: "aliment",
    item_type: "product",
    stock: 50,
    shop: "mock-1",
    shop_name: "Épicerie du Centre",
    is_featured: true,
    photo_url: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&q=80",
    is_mock: true,
  },
  {
    id: "mock-p2",
    name: "Robe en wax africain",
    description: "Magnifique robe en tissu wax africain, coupe moderne et élégante. Disponible en plusieurs tailles. Couture locale de qualité.",
    price: "25000",
    category: "vetement",
    item_type: "product",
    stock: 15,
    shop: "mock-2",
    shop_name: "Boutique Mode Kindu",
    is_featured: true,
    photo_url: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80",
    is_mock: true,
  },
  {
    id: "mock-p3",
    name: "Soin de tresses (pose complète)",
    description: "Pose de tresses africaines par des coiffeuses expérimentées. Toutes longueurs et styles disponibles. Durée : 3-5h selon le style choisi.",
    price: "12000",
    category: "beaute",
    item_type: "service",
    stock: 999,
    shop: "mock-3",
    shop_name: "Salon Beauté Kindu",
    is_featured: false,
    photo_url: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    is_mock: true,
  },
  {
    id: "mock-p4",
    name: "Smartphone Tecno Spark 10",
    description: "Téléphone Tecno Spark 10 4G. Écran 6.6 pouces, caméra 50 MP, batterie 5000 mAh. Garantie 1 an incluse.",
    price: "320000",
    category: "autre",
    item_type: "product",
    stock: 8,
    shop: "mock-4",
    shop_name: "Tech & Électronique",
    is_featured: true,
    photo_url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80",
    is_mock: true,
  },
  {
    id: "mock-p5",
    name: "Huile de palme (5 litres)",
    description: "Huile de palme rouge locale, pure et naturelle. Produite dans la région de Maniema. Idéale pour la cuisine congolaise.",
    price: "8500",
    category: "aliment",
    item_type: "product",
    stock: 120,
    shop: "mock-1",
    shop_name: "Épicerie du Centre",
    is_featured: false,
    photo_url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80",
    is_mock: true,
  },
  {
    id: "mock-p6",
    name: "Chemise ankara homme",
    description: "Chemise homme en tissu ankara. Coupe slim, couleurs vives. Fabriquée localement par des tailleurs de Kindu.",
    price: "18000",
    category: "vetement",
    item_type: "product",
    stock: 20,
    shop: "mock-2",
    shop_name: "Boutique Mode Kindu",
    is_featured: false,
    photo_url: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&q=80",
    is_mock: true,
  },
  {
    id: "mock-p7",
    name: "Réparation téléphone (écran cassé)",
    description: "Service de remplacement d'écran pour tous modèles de smartphones. Délai : 1-2 heures. Pièces d'origine garanties.",
    price: "25000",
    category: "autre",
    item_type: "service",
    stock: 999,
    shop: "mock-4",
    shop_name: "Tech & Électronique",
    is_featured: false,
    photo_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80",
    is_mock: true,
  },
  {
    id: "mock-p8",
    name: "Crème hydratante Shea Butter",
    description: "Crème visage et corps au beurre de karité pur. Hydratation intense, peau douce et lumineuse. 200ml.",
    price: "6500",
    category: "beaute",
    item_type: "product",
    stock: 45,
    shop: "mock-3",
    shop_name: "Salon Beauté Kindu",
    is_featured: false,
    photo_url: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80",
    is_mock: true,
  },
];

// Détails complets pour la page produit (indexed by id)
export const MOCK_PRODUCT_DETAILS = {
  "mock-p1": {
    ...MOCK_PRODUCTS[0],
    currency: "CDF",
    images: [],
    shop_detail: MOCK_SHOPS[0],
    related: [MOCK_PRODUCTS[4]],
  },
  "mock-p2": {
    ...MOCK_PRODUCTS[1],
    currency: "CDF",
    images: [],
    shop_detail: MOCK_SHOPS[1],
    related: [MOCK_PRODUCTS[5]],
  },
  "mock-p3": {
    ...MOCK_PRODUCTS[2],
    currency: "CDF",
    images: [],
    shop_detail: MOCK_SHOPS[2],
    related: [MOCK_PRODUCTS[7]],
  },
  "mock-p4": {
    ...MOCK_PRODUCTS[3],
    currency: "CDF",
    images: [],
    shop_detail: MOCK_SHOPS[3],
    related: [MOCK_PRODUCTS[6]],
  },
  "mock-p5": {
    ...MOCK_PRODUCTS[4],
    currency: "CDF",
    images: [],
    shop_detail: MOCK_SHOPS[0],
    related: [MOCK_PRODUCTS[0]],
  },
  "mock-p6": {
    ...MOCK_PRODUCTS[5],
    currency: "CDF",
    images: [],
    shop_detail: MOCK_SHOPS[1],
    related: [MOCK_PRODUCTS[1]],
  },
  "mock-p7": {
    ...MOCK_PRODUCTS[6],
    currency: "CDF",
    images: [],
    shop_detail: MOCK_SHOPS[3],
    related: [MOCK_PRODUCTS[3]],
  },
  "mock-p8": {
    ...MOCK_PRODUCTS[7],
    currency: "CDF",
    images: [],
    shop_detail: MOCK_SHOPS[2],
    related: [MOCK_PRODUCTS[2]],
  },
};
