# Generated by Django 6.0.5 on 2026-05-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('XAF', 'Franc CFA'), ('USD', 'Dollar')], default='XAF', max_length=3),
        ),
    ]
